import type { Metadata } from "next"
import localFont from "next/font/local"
import { Geist, Geist_Mono } from "next/font/google"
import "@/styles/globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const neueFreigeist = localFont({
  src: [
    {
      path: "../assets/fonts/NeueFreigeist-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueFreigeist-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueFreigeist-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueFreigeist-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-neue-freigeist",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${neueFreigeist.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
